---
title: "CV"
css: /Styles/website_styles.scss
---

Recent (full) CV available [here](media/CV_Franklin_CURRENT.pdf) for download.

## Education

PhD **Geography**, University of Arizona, 2004 (minor: Spatial Analysis and Remote Sensing)

MA **West European Studies**, Indiana University, 1996

BA **French and Political Science** (minors in Italian and Spanish), Indiana University, 1994, With Distinction, *Phi Beta Kappa*

Degré d’Etudes Françaises, Université de Strasbourg, France, 1993

## Appointments

### **Newcastle University**

-   **Head**, Newcastle Data, February 2022–present
-   **Professor of Geographical Analysis**, Centre for Urban and Regional Development Studies (CURDS), School of Geography, Politics and Sociology, 2018–present

### **The Alan Turing Institute**

-   **Group Leader – Liveability**, Science of Cities and Regions Programme (SoCaR), 2023–present
-   **University Lead – Newcastle**, 2021–2023

### **Brown University**

-   **Associate Director**, Spatial Structures in the Social Sciences (S4), 2010–2018\
-   **Associate Professor (Research)**, Population Studies, 2015–2018\
-   **Assistant Professor (Research)**, Population Studies, 2010–2015

### **University of Maryland**

-   **Senior Lecturer**, School of Public Policy and Faculty Associate, Maryland Population Research Center, 2009–2010\
-   **Adjunct Lecturer**, School of Public Policy, 2004–2009

### **American Association of Geographers (AAG)**

-   **Deputy Director**, 2007–2009

### **U.S. Census Bureau**

-   **Statistician Demographer**, Population Distribution Branch, Population Division, 2002–2004

## Visiting Academic Appointments

**Visiting Scholar**, Population Studies, Brown University, 2018–present\
**Visiting Professor**, Gran Sasso Science Institute (GSSI), Italy, 2018–present\
**Visiting Professor**, University of Sassari, Sardinia, Italy, November 2019

## Fellowships and Awards

Fellow, Regional Studies Association, 2024\
Outstanding Service Award, AAG Spatial Analysis and Modelling Specialty Group, 2023\
Fellow, Royal Geographical Society (RGS), 2020–present\
Fellow, Western Regional Science Association (WRSA), 2020–present\
Fellow, Alan Turing Institute, 2018–2023\
David E. Boyce Award for Distinguished Service to the Field of Regional Science, 2015\
Student Paper Award, AAG Population Specialty Group, 2003\
Benjamin H. Stevens Graduate Fellowship in Regional Science, 2001–2002\
Graduate Student Paper Award, AAG European Specialty Group, 2001\
Lander MacClintock Award for Excellence in Italian Studies, 1994\
Phi Beta Kappa, Gamma of Indiana, elected 1994
