---
title: "Research"
css: /Styles/website_styles.scss
---

I am a population geographer with research interests in the sources and impacts of demographic change as it occurs at multiple spatial scales. Demography — age structure, migration patterns, or human capital stocks, for example — is at the core of most social science, health, or environmental challenges facing us. I work at the regional and local scales to understand how best to characterize or measure the populations of places; how location and scale are related to demographic change; and how migration, especially internal, affects demographic composition. I am especially interested in how we use data and statistics to understand what sorts of people are located where, how this changes over time, and what this means for our understanding of spatial inequality.

### Data

Data is the cornerstone of demographic and spatial research. Whether traditional (e.g., census or survey) or new and emerging (e.g., trajectory or sensor), we rely on data to characterise society, understand how it is evolving, and identify social and spatial inequalities. It is therefore imperative to understand our data: sources, characteristics, and attendant strengths and weaknesses. I've written about data [here](https://journals.sagepub.com/doi/full/10.1177/03091325211063635) and [here](https://open.substack.com/pub/rachelfranklin/p/not-the-data-revolution-we-want-but?r=3xp53&utm_campaign=post&utm_medium=web). I also head up the [ESRC Smart Data Research UK (SDR UK)](https://www.ukri.org/what-we-do/browse-our-areas-of-investment-and-support/smart-data-research-uk/) Strategic Advice Team, providing expert knowledge and insight to the ESRC on their £49 million investment into smart data infrastructure and services.

### Spatial Inequality and the Smart City

Smart city technologies, particularly sensors, contribute to and reinforce socio-economic and spatial inequalities. Funded by the [Alan Turing Institute](https://www.turing.ac.uk), this project aims to identify who is affected by 'sensor deserts', ascertain coverage for vulnerable populations, and improve understanding of connections between urban mobility and sensor density and location. This work contributes to a growing body of research that highlights the potential risk of smart cities increasing rather than reducing inequality and quality of life, providing a blueprint to assist cities in better adoption of smart city technologies.

### Left Behind Places, Shrinking Cities, and Depopulation

Recent and ongoing projects address spatial inequality from a landscape perspective: how do we identify, locate, and measure places that are failing to thrive? I have been particularly interested in population loss or shrinkage at the local and regional scales in the United States, with research projects that have focused on the ways in which the degree of loss in any one time period may be mediated or exacerbated by the larger geographical and historical context; the demographic sources of population loss; spatial metrics for urban shrinkage; and the impacts of loss on inequality. These projects have been funded by the National Science Foundation and the National Institutes of Health in the United States. Other research focuses on the measurement of human capital stocks and the relationship between migration and human capital, including research on university student migration flows in the United States. Most recently, as part of a multinational team, funded by the ESRC in the UK, this research has expanded to include multidimensional perspectives on ["Left Behind" neighbourhoods and regions](https://research.ncl.ac.uk/beyondleftbehindplaces/).

### Recent and Currently-Funded Projects

“The SDR UK Imagery Data Service for Sustainability, Prosperity and Wellbeing (Imago),” U.K. Economic and Social Research Council (ESRC), September 2024–March 2029 (Co-Director with Dani Arribas-Bel, £5,430,913)

“Digital Footprints: Strategic Advice Team,” U.K. Economic and Social Research Council (ESRC), January 2023–December 2024 (PI, £521,228)

"Estimating Pandemic Effects on Publication in Regional Studies Journals,” Regional Studies Association, April–September, 2022 (PI, £28,991)

“Beyond 'Left Behind Places': Understanding Demographic and Socioeconomic Change in Peripheral Regions,” U.K. Economic and Social Research Council (ESRC), January 1, 2021–December 31, 2023 (Co-I; £563,618)

“The Impact of the Environment and Pollution on Cognitive Health (EPOCH): Building the knowledge base through international collaboration,” U.K. Medical Research Council (MRC), October 1, 2020–September 30, 2023 (Co-I; £538,704)

“Centre for Doctoral Training in Geospatial Systems,” U.K. Engineering and Physical Sciences Research Council (EPSRC), April 1, 2019–September 30, 2027 (Co-I; £6,718,389)

“Smart Cities and Inequality,” Alan Turing Institute, October 1, 2018–March 31, 2022 (PI; £268,023)
