---
title: "Talks"
css: /Styles/website_styles.scss
---

This is a curated selection...see [CV](/media/CV_Franklin_CURRENT.pdf) for the exhaustive, definitive list.

### Invited Keynotes and Lectures

“[The Quest for Mappiness: Creating Communities of Spatial Practice](https://www.rachelfranklin.org/Talks/Amherst/),” Keynote, “Oh, Mappy Day,” University of Massachusetts, Amherst, April 3, 2026

"[Old, New, Borrowed and BLUE?](https://www.rachelfranklin.org/Talks/RSA_London/)," Keynote, 2025 Regional Studies Association (RSA) Regional Futures Conference, London, November 13, 2025

“[The Tortured Geographers Department](https://www.rachelfranklin.org/Talks/ASU/),” 2025 Malcom L. Comeaux Lecture, School of Geographical Sciences and Urban Planning, Arizona State University, November 7, 2025

“[Spatial Is Special](https://www.rachelfranklin.org/Talks/SDSU_talk/),” Distinguished Getis Lecture in Spatial Analysis, Department of Geography, San Diego State University, California, November 22, 2024

“[21st Century Geographical Methods for Timeless Spatial Inequality Challenges](https://www.rachelfranklin.org/Talks/Vienna/),” Sociotechnical Foundations of GeoAI and Spatial Data Science Workshop, Vienna, Austria, October 26–27, 2024

“The Answer to the Ultimate (Demographic) Question of Life, the Universe, and Everything,” Keynote, IGU Applied Population Geography Research Workshop, University of the Aegean, Lesvos, Greece, September 19, 2023

“The changing data ecosystem in demography. Non‐traditional data sources,” Plenary, with Alice Reid and Andy Tatum, British Society for Population Studies (BSPS) 2022 Conference, Winchester, England, September 5, 2022

“Choose Your Own Adventure: Charting a Fulfilling Professional Path in the Geospatial Sciences,” Keynote, TRELIS 2022 Workshop, University Consortium for Geographic Information Science (UCGIS), Minnowbrook Conference Center, Blue Mountain Lake, New York, June 6, 2022

“Locating the “Left Behind”—Multidimensionality, Scale, and the Role of Demographic Change,” Keynote, From Depopulation to Left-Behind Places: New Challenges, New Policies Workshop, Universitat Jaume I de Castellón (UJI), Castellón, Spain, May 31, 2022

“Sensing Inequality: Smart Cities, Sensor Deserts, and Equitable Decision-Making,” Keynote Address, The 2021 European Colloquium on Theoretical and Quantitative Geography (ECTQG), Manchester, November 5, 2021 (virtual)

“Inequality and the Smart City,” Keynote Address, GeoComputation 2019, Queenstown, New Zealand, September 20, 2019

“I Come to Bury Growth, Not to Praise It,” Keynote Address, Regional Studies Association Annual Conference, Santiago de Compostela, Spain, June 5, 2019

### Invited Presentations and Panels

“[Urban data and the mirage of control](https://www.rachelfranklin.org/Talks/Leuven/),” The Urban in 2035: Data, Methods and the Questions Ahead Symposium, KU Leuven Urban Studies Institute, Belgium, September 25, 2026.

“[Metaphors for 2026: Planning for Metropolitan Change](https://www.rachelfranklin.org/Talks/AMPO/),” Socioeconomic Forecasting Webinar—Quarter 2, Association of Metropolitan Planning Organizations (AMPO), June 23, 2026.

“[Left Behind Places: By the Numbers](https://www.rachelfranklin.org/Talks/Zurich_2026/),” Approaching (Left-Behind-)Places through Geography and Art, Zürich, Switzerland, May 26, 2026.

“[Pixels Aren’t Places](https://www.rachelfranklin.org/Talks/GSSI_SPACERAISE/),” SPACERAISE International Summer School for Space Studies and Interdisciplinary Applications, L’Aquila, Italy, May 20, 2026.

“[Spatial Inequality and the Smart City](https://www.rachelfranklin.org/Talks/Urban_Data_Working_Group/),” Urban Data Working Group/Equity and Access in Algorithms Mechanisms and Optimization (EAAMO) Seminar Series (online), April 27, 2026.

“[Regional Science for Babies](https://www.rachelfranklin.org/Talks/WRSA_2026/),” Discussant remarks, Presidential Address (Alessandra Faggian), 65th Annual Meeting of the Western Regional Science Association, Santa Fe, NM, February 2026.

“[A (spatial) album with 8 tidy tracks](https://www.rachelfranklin.org/Talks/Esri/),” Esri, Redlands, California, February 17, 2026

“[Mind the Temperatures: The challenge of estimating present and future heat exposure on the London Tube](https://www.rachelfranklin.org/Talks/OSU/),” Department of Geography, The Ohio State University, October 24, 2025

“[Data, Data, Data](https://www.rachelfranklin.org/Talks/Lincoln_2025/),” From Global to Local: Policy Frameworks for Digital Governance in Cities Panel, Land Policy Conference: Responsive and Equitable Digitalization in Land Policy, Lincoln Institute of Land Policy, May 23, 2025

“[Rethinking GIS Education in an Age of Disruptions](https://www.rachelfranklin.org/Talks/NE_GIS_2025/),” Northeast Higher Ed GIS Facilitators Meet Up,” Boston University, May 20, 2025

“[AI and Data Innovations for Liveable Cities](https://www.rachelfranklin.org/Talks/Singapore/),” AI and Data Innovation for Sustainability and Infrastructure Conference, Singapore, April 2, 2025

“[Smart but Unequal?: Sensor Infrastructure in the Smart City](https://www.rachelfranklin.org/Talks/Cambridge/),” City Seminar Series, University of Cambridge, February 25, 2025

“[Five Red Herrings: The Role of Data, Data Science, and AI in Population Health Research](https://www.rachelfranklin.org/Talks/Herrings/),” Population Health Sciences Institute (PHSI) Christmas Research Event, Newcastle University, December 11, 2024

“Mind the Gap: Estimating present and future heat exposure on the London Tube,” METRANS, Sol Price School of Public Policy, University of Southern California, September 25, 2024

“[Don’t Panic!](https://www.rachelfranklin.org/Talks/SCAG/#/),” 2024 Southern California Demographic Workshop, Southern California Association of Governments (SCAG), Los Angeles, California, September 24, 2024

“Spatial Inequality and the Smart City,” Bartlett School of Planning Public Lecture, UCL, London, January 25, 2024

"[Disruptions, Engagement, and ~~GIScience~~ Solutions](https://www.rachelfranklin.org/Talks/UCSB_Disruptions/)," Spatial Data Science in an Age of Scientific Disruption Workshop, Santa Barbara, California, December 7–8, 2023

“Thinking about ‘progress’ in quantitative methods,” Department of Human Geography, Lund University, October 4, 2023

“Lost in Translation?: Connecting the conceptual and methodological to locate the “Left Behind,” Intersections Seminar, Department of Geography and Planning, University of Toronto, April 28, 2023

“How have place-based policies evolved to date and what are they now?”, Invited Contribution, Workshop, OECD, Paris, April 14, 2023

“Future Directions for Urban Analytics and City Science,” Panel, Annual Meeting of the Association of American Geographers, Denver, CO, March 23–27, 2023

### Recent Conference Presentations

“[Good Data Is Hard to Find: Why this matters and what to do about it](https://www.rachelfranklin.org/Talks/AAG_2026/),” Annual Meeting of the Association of American Geographers, San Francisco, CA, March 17–21, 2026.

“[Why Digital Twins Matter (Do They?)](https://www.rachelfranklin.org/Talks/CGA_digital_twins/),” Engaging the Next Generation: Why Do Digital Twins Matter?, Center for Geographic Analysis (CGA) Conference, Harvard University, May 23, 2025

“Landscape of Loss: A Spatiotemporal Contextual Approach to Measuring U.S. County-Level Depopulation,” (co-authored with Gainbi Park and Eric Seymour), Population Association of America (PAA) Annual Meeting, Washington, DC, April 10–13, 2025.

“Lost in transition? Trajectories of regional ‘left-behindness’ in the EU15 from 1982 to 2017,” (co-authored with Mehdi Le Petit-Guerin, Sanne Velthuis, Jeroen Royer, Nicolas Cauchi-Duval, Tim Leibert, Danny MacKinnon, and Andy Pike), Annual Meeting of the Association of American Geographers, Denver, CO, March 23–27, 2023
